language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - iojs-v1
  - iojs-v2
script: npm test
before_script:
  - npm install
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
env:
  global:
    - secure: v2bejH19uVm/1XedVESa6ubkm1bLnZWUgOxtOx/cLRTYZ3iHPHDZJk4h+HdsIhpIy9mbSgGrHsz/FlVXQ/qmpwvQrrD0/wt8NQ7XhuV+O8e1/qLXNMQWixhJQTa1q9m+qP04IrJML9dHy+9pIpzUBMhRm0FWmAZtkYkX3D1L9d78anBCCZIYaWPPiNhoERLcqIm6PDmhLjk7YLvS04Gf+Zmzlhd7glwmLu4K2m2z7RdaPVTs8rRnp70ZUePEVgWDqmv8T9QGPpIXdvLTJBfAv4zTGws1U4z8nF5I5QpbsudtYWsbxXg6/j8oz9AmjDoMLLuiLHxrpFn8S/XU3degF1temaVABRxF6JUQ7VCDBDHmAxF0gVhdn5+Ily0f4pdOg3Tge/U/JR10y+3G1RwEZTydyja43i0zohiWKVT7kZ53u96WSouOjDCbMYm9E+b4vPr3Kl5bCaog0BFBJu33X8fduojROM/QUQFp99+a9/8mBtKjoGfzEk06gN0+5Ux8mkBQAaV0gty31Mqp4tvyYX+8NsrrUxF6cfXDnkIwA2c3L87gVfbtjpBFu1ycLsH84nH3c4NSTp5hpl5xc62x996WnyRnFk0CQLiHshhPDBuqfCmPlKtSnuH8aE8QaoToUtwUz2FL6oSDcm3lway6j1/RzBixw4xd71TaYubte38=
    - secure: TuzTRCraWLJY1sV+espwzz86UN3W2kDXsQQIy5H0IllLZPsrsgTBTFeEmR+s+3WvkXMHjS9QlBgfQtp7npVANQoSBnujC0RS/uvQGy9DTL/t2P/DY64yPCIXjHi0/WRJbDUj8SgxOQ6AE/VEKYoRpijnIsL9dC8N7hnw76W+/Sc8JWfnkrM8a99k4ARw2FVelxhpMEQCOvd4O56JVt3DmhP0p1mpy3KWRkSFB2XgjHuu1IsDXUvEKr5Bd5sH2PK6pq3JsynVGKQeZ1iTPt+/sd17uW6j6G08eq07YwPW4kbi1C+A1D8hIZO3GxJ9HuXwPcwSi6JuSyB4TAPBOJhkuY497/J6mVoIkVAw5D12sUHCdYZLfDvP3R+V2NJdfGbwhaJoW1kNhJY6lTQYT/0GqolhZWwsy5QZ1/QRTl9utk8rkTmcJ0VntAB0Fq6LaFcqml7rIqEd3JhkG8U//9Swb5xeZhxp9hiiUb9QuyWPpXbVIbDza7miuPyP5B46l9wgqzzIHqsAUl1JWotoeFkj6px3tk+ek8miaMibsRp33IciX42x6u7Q0hmsBGOv3NwMGjv+KZBWoB+gFmmQRTJijDih/awbCADj9oNgf8n6eZ7zqRAV0g7FFIKKCqJWaXkC2i7xpOY8zFFmMIjgQnNtBnDP5p6IcsXSNnH0IyrA/K8=
