language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- 'iojs-v1'
- 'iojs-v2'
script: npm test
before_script:
- npm install
env:
  global:
  - secure: V/AHOSvodGSBPWKv9V80NDybExvzQN2VC8X0NO3TWbsMxBkf8Nr5FJW4T82DZYTmk4IE4CDR7Asxr+AEUUKqDcZKuZiI/379TGHUPJvZVpeIWymiyzeh+qJVK5nvBudBgU1LkwKZnF3Ka1fo5l4S6eJLl7iwpbRwWGtQg1WN0T0ntxaj4MefU7x+DxyKecVphJiXavB/ftKy3UOMO86CgJPpVGEpRmHHTnQpDL1Q8hBifgfBvsCNEgk5Ug2ZfLStFbL993dVyh0wgIf4GYTPS9FETOBlAdXAADqHYZfr6SOCxkmUbF5F/K2Lz/vzA6XhvkHOIl8tzoO5sqS8fs+EPrnlpP6PkvKb2Ah5Yx+1ZFuVvfJ1dMDyl0Ugw1T1uZqPESNCUIkrC2BLMADjoi4v33D7FKeG9uJ/bcxjSIwpH6DNCHXkkiLg2vZpWC+kuL91Kfa7uxzqsYMFwDvTp727Fu3iMTlKqK7PwfZgBcklT5v1gmlfS9DR57Qm9bYPxgk9rcI2ed9zE/zKg30X/klVHgDdJDrfCWYsAVqHA3n/hWVDGnEyJ9XTPiwZQIX1RsCe5pZDB4qwpmbJ9qljgnzgBLciWIL6+qenYzJvOdC6Q0Ev2uLyC44WYrqJhnMpGqB0j2FZHtdrJw+GZ9xC5DbzID4eSyP9ZVRhhZTzeAgps9c=
  - secure: MsnV7Ggk/D5GyVhQf578HgWN7UHkZD6hMpIlPCQE+2+a0yYVFp8x/+uTSOa9ek5s9W9nHpwtprwF+CMBGaDvBMgn7M6PxJTXLRx3gyur8XaGHp8M60i5Edt4vBEi/+8I+PPk8IpfLm32nqq6scxGSdjEdsldlQqm2yKmhjQZlAUh9QdbSlLeQVn+DYH5zKQuh458d4vhVNkX2kN78DQ2CEqODc56hdJnDmTMPNWFqVl85ELwQgWUD8A6dTJwO+hzFX6umisItAR46WBODlAdqBifw8laxfHiHdZzf2LOXBGHnQJfTu4y0eQHKkCxwPbDVfIsCnf2rp5fzi+OUJF/2uW7ZxFiew/j2D3dSWiG+ZBwS1tAT8C4e0BCQcO/DZ/4Usr7jT1gnrR5/4u6Xq1SJOL/tFK4OP/7zfDivZcaGGu7hXbu8rhcyauppZcZoaKI7gm/rpnUgPg5y/bCKVKbQxsvFf058LBhVy+cQuFJLUt+tr1Gr2kPX4w/RnnN0zntpuN8nJyUplDplZrDmyZAPtZr5w6pPdtZELWf8EIJcvyTo17xWBPa1k/w0y7DvbzdZmejDuwqpIuiTjUDRG1MLN/Or1R8NFaIC8nlRmrYvfi8/1b6oB4jXJncqqzEYiMG5YVPMDj27JVBFs1qB1PN17F+zkD9TXN0M+0dj0xMwa4=
